<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>dra</string>
	</array>
	<key>name</key>
	<string>DRAMA</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Comment</string>
			<key>match</key>
			<string>\|(.*)</string>
			<key>name</key>
			<string>comment.dra</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Registers R0-R9</string>
			<key>match</key>
			<string>\b(R[0-9])\b</string>
			<key>name</key>
			<string>constant.language.dra</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(HIA|OPT|AFT|BIG|VER|VGL|VSP|SPR|DEL|MOD|RESGR|SBR|BST|HST)\b</string>
			<key>name</key>
			<string>keyword.dra</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Comparison variables</string>
			<key>match</key>
			<string>\b(NUL|NNUL|POS|NPOS|NEG|NNEG|GEL|NGEL|GRG|GR|KL|KLG)\b</string>
			<key>name</key>
			<string>keyword.dra</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Special keywords without parameters</string>
			<key>match</key>
			<string>\b(LEZ|DRU|STP|EINDPR|DRS|NWL|KTG)\b</string>
			<key>name</key>
			<string>entity.name.function.dra</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Constant numeric</string>
			<key>match</key>
			<string>[-+]?\b\d+\b</string>
			<key>name</key>
			<string>variable.parameter.dra</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.dra</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>String highlighting</string>
			<key>match</key>
			<string>(\w.*(?=:))|([a-zA-Z0-9_]+(?=\n))|([a-zA-Z0-9_]+)(?=( *\||\())</string>
			<key>name</key>
			<string>string.dra</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.dra</string>
	<key>uuid</key>
	<string>b82b89af-334e-46b5-aaff-1858275ccff1</string>
</dict>
</plist>
